### ISSUE TITLE
The Snapshot Response link does not work correctly

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/cloud-manager-automation#38]
Page: [Resources](https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_resources.html)

In the GET /gcp/ha/volumes/{workingEnvironmentId}/{svmName}/{volumeName}/snapshots

There is a link for the response of this GET:

<html><body>
<h5 id="responses-212">Responses</h5>

HTTP Code | Description | Schema
-- | -- | --
default | success | SnapshotResponse array

</body>
</html>Responses
HTTP Code 	Description 	Schema

default
	

success
	

[SnapshotResponse](https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_definitions.html#snapshotresponse) array

This link just takes you back to the top of the page, it does not show the SnapshotResponse definition.

**Comment by netapp-ranuk** [comment]
Thanks, Richard. We'll fix this link as soon as we can.

**Comment by netapp-ranuk** [comment]
The issue has been fixed. Page: [Resources](https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_resources.html) [Definitions](https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_definitions.html)
