### ISSUE TITLE
"Client credentials" grant type api json 

### ISSUE THREAD

**Issue by guypar** [NetAppDocs/cloud-manager-automation#51]
Page: [Grant types and identity verification](https://docs.netapp.com/us-en/cloud-manager-automation/platform/grant_types.html)

    "audience": "https://api.cloud.netapp.com"

Should be added to the json of "Client credentials" grant type
{
    "audience": "https://api.cloud.netapp.com"
    "grant_type": "client_credentials",
    "client_id": "<CLIENT_ID>",
    "client_secret": "<CLIENT_SECRET>"
}
otherwise this error will be raised:
{
    "error": "access_denied",
    "error_description": "No audience parameter was provided, and no default audience has been configured"
}

**Comment by netapp-ranuk** [comment]
Thank you for your comment. We'll get back soon on this.

**Comment by dmp-netapp** [comment]
This issue is now fixed and live. Added to "client credentials" grant type. Will leave this issue open for a few days to confirm.
