### ISSUE TITLE
Incorrect entry for example curl command

### ISSUE THREAD

**Issue by felix-melligan** [NetAppDocs/cloud-manager-automation#54]
Page: [Create user token](https://docs.netapp.com/us-en/cloud-manager-automation/platform/create_user_token.html)

Hi all,

So the example curl command in the docs is: curl --location --request POST 'https://netapp-cloud-account.auth0.com/oauth/token' --header 'Content-Type: application/json' --d @JSONinput

But the command will fail, the "--d" is incorrect - it should either be "-d" or "--data". We've also had some feedback that the "@JSONinput" part is slightly confusing.

Really appreciate the docs!

Many thanks,

Felix

**Comment by netapp-ranuk** [comment]
Thanks for your comment. We'll get back on this soon.

**Comment by dmp-netapp** [comment]
This issue is now fixed and live. Will leave this issue open for a few days for you to confirm.
