### ISSUE TITLE
Broken Link - https://docs.netapp.com/us-en/cloud-manager-automation/cm/getting_started.html

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-automation#66]
Page: [Before you begin](https://docs.netapp.com/us-en/cloud-manager-automation/cm/wf_azure_before.html)

https://docs.netapp.com/us-en/cloud-manager-automation/cm/getting_started.html

Thx
Holger

**Comment by netapp-ranuk** [comment]
Thank you for highlighting this. We'll fix this as soon as possible.

**Comment by netapp-ranuk** [comment]
Hi @kholger, we've fixed the broken link in the Before you begin pages for each of the cloud providers https://docs.netapp.com/us-en/cloud-manager-automation/cm/wf_aws_before.html.
