### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/cloud-manager-automation#78]
Page: [Send audit information](https://docs.netapp.com/us-en/cloud-manager-automation/audit/post-exteranl-audit.cloudmanager.netapp.com.html)

Looks like a typo in the POST endpoint:

/exter**an**l-audit.cloudmanager.netapp.com

**Comment by netapp-ranuk** [comment]
Thanks, Ben. We noticed the typo, however, because this URL is referenced by other internal services, I think we are not in a position to revise this. Nonetheless, I will check with Engineering and will get back, thanks for flagging this.

**Comment by ntap-bmegan** [comment]
This page doesn't even seem to exist anymore.

**Comment by netapp-ranuk** [comment]
We removed the content recently after consulting Ben and the SMEs.
